Use cube for build script
p2gz/p2gz pull request #13
Opened 2024-07-08 15:09 UTC by mayabyte

Had to change the extracted BMG to use cube's format. Otherwise seems to work pretty well

2024-07-08 16:18 UTC, jonathonbrady commented on build.py
>              extracted_archive = os.path.join(iso_path, (set(next(os.walk(iso_path))[1]) - existing_directories).pop())
Minor thing but if cube allows specifying the name of the output folder I would prefer to do that and remove both of the surrounding lines here since they were only necessary for ArcExtract.

2024-07-08 16:38 UTC, mayabyte commented on build.py
>              extracted_archive = os.path.join(iso_path, (set(next(os.walk(iso_path))[1]) - existing_directories).pop())
it does yeah, let me give that a shot

2024-07-08 19:05 UTC, jonathonbrady commented
Is ISO extraction functional in cube? We could remove the dependency on nodtool while we're here.

2024-07-09 10:43 UTC, mayabyte commented
It is, but it's a lot slower than nodtool (and caveripper for that matter, which is weird because they use the same library). I haven't had the chance to optimise that yet so I'd prefer to switch it over later on.

2024-07-11 00:51 UTC, jonathonbrady commented
Ran `python3 build.py --clean` and am getting the following crash when trying to load one of the custom menus:
![oks71OP](https://github.com/p2gz/p2gz/assets/62264079/355ef5b0-b8ce-466e-ad83-00ffec692693)

2024-07-11 08:12 UTC, mayabyte commented
fuck!!

2024-07-12 14:17 UTC, mayabyte commented
Cube 0.4.7 addresses the problem 👍

2024-07-13 01:11 UTC, jonathonbrady requested changes

2024-07-13 01:11 UTC, jonathonbrady commented on build.py
> -                                       {os.path.join(extracted_archive, file.replace("json", "bmg"))}', shell=True, stdout=open(os.devnull, 'w'))
Pulled the latest and ran `python3 build.py --clean`. I think the build script is just extracting and repacking `mesRes_eng` without packing `pikmin2.bmg.json`, as none of the custom messages show up:
![](https://i.imgur.com/LbmBxz2.png)

2024-07-13 09:02 UTC, mayabyte commented on build.py
> -                                       {os.path.join(extracted_archive, file.replace("json", "bmg"))}', shell=True, stdout=open(os.devnull, 'w'))
ah, wasn't sure what that was supposed to look like. seems like it was somehow an issue with the copytree call, fixed now

2024-07-14 02:57 UTC, jonathonbrady submitted a review, later dismissed

2024-07-14 08:02 UTC, mayabyte commented
Whoops lol, idk how I missed that. Fixed now

2024-07-14 08:39 UTC, jonathonbrady approved these changes

2024-07-14 08:51 UTC, merged